name: Configure Windows 11 RDP

# Jalankan workflow ini secara manual dari tab Actions
on:
  workflow_dispatch:

jobs:
  configure-rdp:
    # INI PALING PENTING: Runner harus jalan di Windows 11 Anda
    runs-on: self-hosted

    steps:
      - name: Checkout code (optional)
        uses: actions/checkout@v4

      - name: Enable Remote Desktop
        run: |
          # Aktifkan RDP di registry
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          # Aktifkan rule firewall untuk RDP
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          Write-Output "✅ Remote Desktop has been enabled."

      - name: Set a secure password for current user
        run: |
          # Password diambil dari GitHub Secrets, JANGAN ditulis langsung di sini!
          $Username = "${{ env.USERNAME }}"
          $SecurePassword = ConvertTo-SecureString "${{ secrets.RDP_PASSWORD }}" -AsPlainText -Force
          
          # Gunakan perintah 'net user' untuk mengubah password
          net user $Username "${{ secrets.RDP_PASSWORD }}"
          
          Write-Output "✅ Password for user '$Username' has been updated via net user."

      - name: Display Connection Information
        run: |
          # Coba dapatkan IP Public (jika ada)
          try {
            $PublicIP = (Invoke-RestMethod -Uri "https://api.ipify.org" -ErrorAction Stop).Trim()
            Write-Output "🌍 Public IP Address: $PublicIP"
          } catch {
            Write-Output "⚠️ Could not retrieve Public IP. You might be behind a router."
          }
          
          # Dapatkan IP Local
          $LocalIP = (Get-NetIPAddress -AddressFamily IPv4 | Where-Object { $_.InterfaceAlias -like 'Ethernet*' -or $_.InterfaceAlias -like 'Wi-Fi*' } | Select-Object -First 1).IPAddress
          Write-Output "🏠 Local IP Address: $LocalIP"
          
          Write-Output "=========================================="
          Write-Output "🚀 TO CONNECT:"
          Write-Output "1. Use Remote Desktop Connection (mstsc)"
          Write-Output "2. Enter the IP address above"
          Write-Output "3. Username: ${{ env.USERNAME }}"
          Write-Output "4. Password: [The one stored in your secrets]"
          Write-Output "=========================================="
          Write-Output "⚠️ NOTE: If you're behind a router, you MUST set up port forwarding for port 3389 to this machine's local IP ($LocalIP)."
